# Serverless REST API
# https://github.com/serverless/examples/tree/master/aws-node-rest-api-with-dynamodb

service: tiny-cms-backend # NOTE: update this with your service name

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

provider:
  stage: local
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  deploymentBucket:
    name: tiny-cms # MANUAL ACTION REQUIRED - use same region
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: docs
          method: post
          cors: true

  list:
    handler: handler.list
    events:
      - http:
          path: docs
          method: get
          cors: true

  get:
    handler: handler.get
    events:
      - http:
          path: docs/{id}
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: docs/{id}
          method: put
          cors: true

  # delete:
  #   handler: handler.delete
  #   events:
  #     - http:
  #         path: docs/{id}
  #         method: delete
  #         cors: true

resources:
  Resources:
    DocsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}